<?php
/**
 * Created by PhpStorm.
 * User: Ikars-UVS
 * Date: 2018.07.30.
 * Time: 17:09
 */

/**
 * Class Participants - class to store persons data, extends database connection
 * class to access and store persons data in database
 */
class Participants {

    /**
     * private person properties (p_name - name entered at test selection screen, db_id - identification in database,
     * unique_id - unique value generated by to gat correct data from database)
     */
    private $name;
    private $unique_id;
    private $id;

    /**
     * Participants constructor - used as value setter, calls two functions to set data in db,
     * and receive person id from database
     * @param $id - user id
     * @param $name - persons name
     * @param $unique_id - php generated unique id
     */
    public function __construct($id, $name, $unique_id)
    {
        $this->id = $id;
        $this->name = $name;
        $this->unique_id = $unique_id;

    }

    /**
     * Persons parameter getters
     */
    public function getPersonName(){
        return $this->name;
    }
    public function getPersonsUId(){
        return $this->unique_id;
    }
    public function getPersonsDBId(){
        return $this->id;
    }


}